- type: job
  id: NanoTrasenEmployee
  name: NanoTrasen Employee
  description: "Contracters who work under NanoTrasen and its mmany, many subsidiaries."
  playTimeTracker: JobNanoTrasenEmployee
  startingGear: NanoTrasenEmployeeGear
  icon: "JobIconNanotrasen"
  joinNotifyCrew: false
  alwaysUseSpawner: true
  supervisors: job-supervisors-centcom
  access:
  - NanoTrasenAccess1
  setPreference: true

- type: startingGear
  id: NanoTrasenEmployeeGear
  subGear:
  - PassengerPlasmamanGear
  equipment:
    jumpsuit: UniformNanoEmployee
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: PassengerPDA
  innerClothingSkirt: ClothingUniformJumpskirtColorGrey
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
